---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: k3s_masters
  become: yes
  roles:
    - role: k3s/master

- hosts: k3s_nodes
  become: yes
  roles:
    - role: k3s/node
